config/routes.rb
ComposerProfile::Application.routes.draw do

  
  root to: "works#index"
  get 'composer', to: 'composer#index'

  devise_for :users#, :skip => [:registrations]
  #as :user do
    #get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    #put 'users' => 'devise/registrations#update', :as => 'user_registration'
  #end
  resources :works
  resources :admin
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ActiveRecord::Base
# use "vimeo_id" to retrieve the corresponding "thumbnail_medium", 
# and "url", and add it to the model object.
require 'open-uri'
  before_save :get_thumbnail

  private
    def get_thumbnail
       #FIXME pay attention to class/instance delineation
       #NOTE: move me to the top because i'm a require
       self.vimeo_id #no params in models
       thumbnail = open("http://vimeo.com/api/v2/video/#{self.vimeo_id}.json").read
       thumbnail = JSON(thumbnail).first
       self.vimeo_thumbnail = thumbnail["thumbnail_large"] # no params in models
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  #before_action :find_work
  before_filter :authenticate_user!
  
  def index
    @works = Work.all
    @work = Work.new
  end

  def new
    @work = Work.new
  end

  def edit
    @work = Work.find(params[:id])
  end

  private
    def find_work
      @work = Work.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/composer_controller.rb
class ComposerController < ApplicationController 
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  # NOTE: add helper method to return permitted params private method. 
  before_filter :authenticate_user!, only: [:create, :update, :destroy]
  
  def index
    @works = Work.order(created_at: :desc)
  end

  def create                                                    #add a new work.
    Work.create params[:work].permit(:name, :url, :vimeo_id)    #makes a new db entry with 
    redirect_to '/admin'                                        #takes user back to admin page
  end                                                           #showing all works including the new one.

  def update
    @work = Work.find params[:id]
    @work.update params[:work].permit(:name, :url, :vimeo_id)
    redirect_to '/admin'
  end

  def destroy
    @work = Work.find(params[:id]).destroy
    redirect_to '/admin'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_form.html.erb
<!doctype HTML>
<html>
  <body>
    <div id="form">
      <%= form_for @work do |f| %>
        <%= f.label :Title %>
        <%= f.text_field :name %><br />
        <%= f.label(:vimeo_id,"Vimeo Id") %> 
        <%= f.text_field :vimeo_id %><br />
        <%= f.label :url %>
        <%= f.text_field :url %><br />
        <%= f.submit %>
      <% end %>
    </div>
  </body>
</html>

app/views/admin/edit.html.erb
<!doctype HTML>
<html>
  <body>
    <h1>Edit Page</h1>

    <h3>Update Work</h3>
    <%= render partial: 'form' %>
  </body>
</html>

app/views/admin/index.html.erb
<div>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>
  <br>
  <% @works.each do |work| %>
  <div><b>Title:</b>  <%= work.name %></div>
  <div><b>Vimeo URL:</b>  <%= work.url %></div>
  <div><b>Vimeo ID:</b> <%= work.vimeo_id %></div>
  <div><b>Db Id:</b>  <%= work.id %></div>
  <div><b>Date Created:</b> <%= work.created_at %></div>
  <%= link_to "Edit", edit_admin_path(work.id) %>
  | <%= link_to "Delete", work_path(work.id), :method => :delete %>
<br></br>
<% end %>
<h3>Add Work</h3>
<%= render partial: 'form' %>

app/views/composer/index.html.erb
<!doctype HTML>
<html>
  <body>
    <p>coming soon...i promise...and man,it is going to be cool...</p>
  </body>
</html>
<%= link_to 'home', works_path %>

app/views/layouts/_edit.html.erb
<div><strong>'Partial for EDIT WORK Form'</strong></div>
<%= form_for Work.new do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.label :vimeo_id %>
  <%= f.text_field :vimeo_id %>
  <%= f.label :url %>
  <%= f.text_field :url %><br />
  <%= f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<div class="header">
    <div class="name">
      <h1>mike hughes</h1>
    </div>
    <div class ="title">
      <h2><%=link_to 'composer', composer_path %></h2>
    </div>
    <div class="contact">
      <a href="mailto:michaelryanhughes@gmail.com"><h2>contact</h2></a>
    </div>
    <div class="bar"></div>
</div>
  <div class ="container">

app/views/layouts/_header.html.slim
.header
  .name
    h1 MICHAEL HUGHES
    h3 \ composition \ sound design \ mixing \
.navcontainer
  ul
    /!li = link_to 'composer', composer_path
    li = link_to 'contact', "mailto:michaelryanhughes@gmail.com"
    li = link_to 'sound cloud', "https://soundcloud.com/wittches"
    /!li = link_to 'video game', "#"

app/views/layouts/_thumbnail_grid.html.slim
.grid
  - @works.each do |work|
    <div id="#{work.vimeo_id}" class="white-popup mfp-hide">
      <iframe src="//player.vimeo.com/video/#{work.vimeo_id}" width="700" height="526" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      h3
        = work.name.upcase
        span &#8679
    </div>
    .thumbnail 
      img src= work.vimeo_thumbnail class= "grayscale"
      .title
        p
          = work.name
        a.play-button href="##{work.vimeo_id}" &#x25b6

app/views/layouts/application.html.slim
doctype html

html
  head
    title
      | Michael Hughes

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    p.notice = notice
    p.alert = alert

    body
      = render partial: 'layouts/header.html.slim'
      = yield

app/views/works/index.html.slim
= render partial: 'layouts/thumbnail_grid.html.slim'